### ISSUE TITLE
Can't start development server

### ISSUE THREAD

**Issue by daveliepmann** [mhuebert/maria#200]
### Issue:
I tried to start the development server by following instructions in the readme. In the past this has worked well but today I get this at `yarn run watch`:

```shell
[2018-05-10 10:36:45 - WARNING] HTTP startup failed
java.lang.IllegalArgumentException: XNIO001001: No XNIO provider found
	at org.xnio.Xnio.doGetInstance(Xnio.java:270)
	at org.xnio.Xnio.getInstance(Xnio.java:187)
	at io.undertow.Undertow.start(Undertow.java:116)
	at shadow.undertow$start.invokeStatic(undertow.clj:194)
	at shadow.undertow$start.invoke(undertow.clj:158)
	at shadow.cljs.devtools.server$start_http$fn__29179.invoke(server.clj:140)
	at shadow.cljs.devtools.server$start_http.invokeStatic(server.clj:139)
	at shadow.cljs.devtools.server$start_http.invoke(server.clj:135)
	at shadow.cljs.devtools.server$start_system.invokeStatic(server.clj:219)
	at shadow.cljs.devtools.server$start_system.invoke(server.clj:190)
	at shadow.cljs.devtools.server$start_BANG_.invokeStatic(server.clj:326)
	at shadow.cljs.devtools.server$start_BANG_.invoke(server.clj:316)
	at shadow.cljs.devtools.server$start_BANG_.invokeStatic(server.clj:319)
	at shadow.cljs.devtools.server$start_BANG_.invoke(server.clj:316)
	at shadow.cljs.devtools.server$from_cli.invokeStatic(server.clj:442)
	at shadow.cljs.devtools.server$from_cli.invoke(server.clj:418)
	at shadow.cljs.devtools.cli$blocking_action.invokeStatic(cli.clj:143)
	at shadow.cljs.devtools.cli$blocking_action.invoke(cli.clj:130)
	at shadow.cljs.devtools.cli$main.invokeStatic(cli.clj:191)
	at shadow.cljs.devtools.cli$main.doInvoke(cli.clj:146)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.core$apply.invokeStatic(core.clj:661)
	at clojure.core$apply.invoke(core.clj:652)
	at shadow.cljs.devtools.cli$_main.invokeStatic(cli.clj:233)
	at shadow.cljs.devtools.cli$_main.doInvoke(cli.clj:231)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.core$apply.invokeStatic(core.clj:657)
	at clojure.main$main_opt.invokeStatic(main.clj:317)
	at clojure.main$main_opt.invoke(main.clj:313)
	at clojure.main$main.invokeStatic(main.clj:424)
	at clojure.main$main.doInvoke(main.clj:387)
	at clojure.lang.RestFn.applyTo(RestFn.java:137)
	at clojure.lang.Var.applyTo(Var.java:702)
	at clojure.main.main(main.java:37)
```

### Environment:
I'm on latest master (8943a87d28b0bd7f78dd3424dcc034eb1745f3a6)

**Comment by mhuebert** [comment]
Relevant discussion here: https://clojurians.slack.com/archives/C6N245JGG/p1525325002000089

looks like a more recent version of `deps` is required.

**Comment by avidrucker** [comment]
Is this issue to be resolved in the slated near future?

**Comment by avidrucker** [comment]
> Relevant discussion here: https://clojurians.slack.com/archives/C6N245JGG/p1525325002000089
> 
> looks like a more recent version of `deps` is required.

I'm thinking that it's pretty unlikely (but not out of the realm of possibilities) that some bugs/errors may arise as a result of updating to a more recent version of `deps`. Are there any other factors that come to mind that must be considered before updating to a more recent version of `deps`?

**Comment by daveliepmann** [comment]
I think this is well deprecated
